exclude_paths:
  - 'cms/server/admin/static/jq/**'
  - 'cms/server/admin/static/sh/**'
  - 'cms/server/contest/static/css/**'
  - 'cms/server/contest/static/js/**'
  - 'cms/server/static/jq/**'
  - 'cms/contrib/loaders/polygon/testlib.h'
  - 'cms/ranking/static/lib/**'
  - 'cms/testsuite/code/**'
  - 'cms/testsuite/tasks/*/code/**'
  - 'docs/**'
