services:
  devdb:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./.dev/postgres-data:/var/lib/postgresql/data"

  devrabbitmq:
    image: rabbitmq:4.0

  devredis:
    image: redis:7

  devcms:
    build: .
    depends_on:
      - "devdb"
      - "devrabbitmq"
      - "devredis"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-devdb.conf
      RABBITMQ_URL: pyamqp://guest@devrabbitmq//
      REDIS_URL: redis://devredis:6379/0
    volumes:
      - "./.dev/home:/home/cmsuser"
      - ".:/home/cmsuser/cms"
    privileged: true
    cgroup: host
    command: >
      wait-for-it devdb:5432 -- bash
    ports:
      - 8888:8888
      - 8889:8889
      - 8890:8890
