version: "3.3"

services:
  cms_test_db:
    container_name: cms_test_db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  cms_test:
    container_name: cms_test
    build: .
    depends_on:
      - "cms_test_db"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-testdb.conf
      # Could be removed in the future, see:
      # - https://github.com/pytest-dev/pytest/issues/7443
      # - https://github.com/actions/runner/issues/241
      PYTEST_ADDOPTS: --color=yes
    volumes:
      - "./codecov:/home/cmsuser/cms/codecov"
    privileged: true
    command: >
      wait-for-it db:5432 -- sh -c "
      dropdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      createdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      sudo chown cmsuser:cmsuser ./codecov ;
      pytest --cov . --cov-report xml:codecov/unittests.xml ;
      dropdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      createdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      cmsRunTests -v --coverage codecov/functionaltests.xml ;
      "
