name: cms

services:
    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: cmsuser
            POSTGRES_DB: cmsdb
        volumes:
            - ./volumes/db:/var/lib/postgresql/data

    core:
        image: ghcr.io/edomora97/cms-core
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Rome
        volumes:
            - ./volumes/config:/config
        ports:
            - 8889:8889

    ps:
        image: ghcr.io/edomora97/cms-ps
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Rome
            CMS_SHARD:
        volumes:
            - ./volumes/config:/config

    cws:
        image: ghcr.io/edomora97/cms-cws
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Rome
        volumes:
            - ./volumes/config:/config
        ports:
            - 8888:8888

    worker:
        image: ghcr.io/edomora97/cms-worker
        deploy:
            replicas: 4
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Rome
        volumes:
            - ./volumes/config:/config
        privileged: true
        cgroup: host

    ranking:
        image: ghcr.io/edomora97/cms-rws
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Rome
        volumes:
            - ./volumes/config:/config
        ports:
            - 8890:8890
