FROM ghcr.io/edomora97/cms-base

LABEL org.opencontainers.image.source=https://github.com/edomora97/cms
LABEL maintainer="Edoardo Morassutto <edoardo.morassutto@gmail.com>"

ENV CMS_CONTEST_ID=
ENV CMS_PROXY_SERVICE_DISABLED=false

COPY docker/core/root /
EXPOSE 8889
