#!/usr/bin/with-contenv bash

CMS_DOC_PATH=${CMS_DOC_PATH:-/config/doc}

if [ ! -d "$CMS_DOC_PATH" ]; then
    echo "C++ documentation is missing, copying..."

    mkdir -p "$CMS_DOC_PATH"
    cp -r /defaults/doc/reference/* "$CMS_DOC_PATH"
    chown -R "$PUID:$PGID" "$CMS_DOC_PATH"
fi
