#!/usr/bin/with-contenv bash

disabled=${CMS_PROXY_SERVICE_DISABLED:-false}
contest_id=${CMS_CONTEST_ID}

if [ "$disabled" != "false" ]; then
    exit 0
fi

if [ -n "$contest_id" ]; then
    exec cmsProxyService -c "$contest_id" 0
else
    echo | exec cmsProxyService 0
fi
