name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cgroup-lite

      - name: Run tests
        run: |
          mount
          #cmsRunTests -v --coverage --codecov
