name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            cgroup-lite \
            cppreference-doc-en-html \
            fp-compiler \
            git \
            haskell-platform \
            libcap-dev \
            libcups2-dev \
            libffi-dev \
            libpq-dev \
            libyaml-dev \
            mono-mcs \
            openjdk-8-jdk-headless \
            postgresql-client \
            php7.4-cli \
            python3-pip \
            python3.8 \
            python3.8-dev \
            rustc \
            zip

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

          python --version
          pip --version

          sudo python prerequisites.py -y --cmsuser=$USER install
          sudo python setup.py install

      - name: Set up database
        env:
          PGPASSWORD: postgres
        run: |
          psql --host=localhost --username=postgres --command="CREATE USER cmsuser WITH PASSWORD 'your_password_here';"

          createdb --host=localhost --username=postgres --owner=cmsuser cmsdb
          psql --host=localhost --username=postgres --dbname=cmsdb --command='ALTER SCHEMA public OWNER TO cmsuser'
          psql --host=localhost --username=postgres --dbname=cmsdb --command='GRANT SELECT ON pg_largeobject TO cmsuser'

          createdb --host=localhost --username=postgres --owner=cmsuser cmsdbfortesting
          psql --host=localhost --username=postgres --dbname=cmsdbfortesting --command='ALTER SCHEMA public OWNER TO cmsuser'
          psql --host=localhost --username=postgres --dbname=cmsdbfortesting --command='GRANT SELECT ON pg_largeobject TO cmsuser'

          cp ./config/cms.conf.sample ./config/cms.conf
          sed -e "s/\"cmsuser\": \"cmsuser\"/\"cmsuser\": \"$USER\"/" -i ./config/cms.conf

          cmsInitDB

      - name: Run tests
        run: |
          cmsRunTests -v --coverage --codecov
