name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check available cgroups
        run: |
          mount | grep cgroup

      - name: Build docker image
        run: |
          docker-compose -f docker-compose.test.yml build cms_test

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm cms_test

      - uses: codecov/codecov-action@v3
        with:
          files: ./codecov/unittests.xml
          flags: unittests

      - uses: codecov/codecov-action@v3
        with:
          files: ./codecov/functionaltests.xml
          flags: functionaltests
